// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daokeefnfivkwohzxqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhb2tlZWZuZml2a3dvaHp4cXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDQ5MTEsImV4cCI6MjA1NzgyMDkxMX0.mHNesSE1Vn8C87XzrXF3KsdVU5fKuTKjLS2qcHb-MDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);