// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txquwknogmiamkehzpac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cXV3a25vZ21pYW1rZWh6cGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjcwMzIsImV4cCI6MjA1NzgwMzAzMn0.5dXsNqJ5lDIjutGqUcOdUY8BxpimbAxZBIF7YY0vp7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);